# API service version with 1 api

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: api-a
spec:
  selector:
    matchLabels:
      app: api-a # has to match .spec.template.metadata.labels
  serviceName: 'api-a'
  replicas: 2 # by default is 1
  template:
    metadata:
      labels:
        app: api-a # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: api-a
          image: hashicorp/counting-service:0.0.2
          ports:
            - containerPort: 9001
              name: http
          nodeSelector:
            failure-domain.beta.kubernetes.io/region: europe-west4-a
