# API service version with 1 api

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: api
spec:
  selector:
    matchLabels:
      app: api # has to match .spec.template.metadata.labels
  serviceName: 'api'
  replicas: 3 # by default is 1
  template:
    metadata:
      labels:
        app: api # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: api
          image: hashicorp/counting-service:0.0.2
          ports:
            - containerPort: 9001
              name: http
