# API service version with 1 api

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: api-b
spec:
  selector:
    matchLabels:
      app: api-b # has to match .spec.template.metadata.labels
  serviceName: 'api-b'
  replicas: 2 # by default is 1
  template:
    metadata:
      labels:
        app: api-b # has to match .spec.selector.matchLabels
      annotations:
        "consul.hashicorp.com/connect-inject": "true"
        "consul.hashicorp.com/connect-service": "api"
        "consul.hashicorp.com/service-meta-zone": "b"
        "consul.hashicorp.com/service-tags": "zone_b"
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: api-b
          image: hashicorp/counting-service:0.0.2
          ports:
            - containerPort: 9001
              name: http
      nodeSelector:
        failure-domain.beta.kubernetes.io/zone: europe-west4-b
