# Central config stored as config map

apiVersion: v1
kind: ConfigMap
metadata:
  name: central-config-routing
data:
  1_web_defaults.hcl: |
    kind = "service-defaults"
    name = "web"
    protocol = "http"
  2_api_defaults.hcl: |
    kind = "service-defaults"
    name = "api"
    protocol = "http"
  3_api_resolver.hcl: |
    kind = "service-resolver"
    name = "api"
    connect_timeout = "5s"
    default_subset = "a"
    subsets = {
      a = {
        filter = "Service.Meta.zone == a"
      }
      b = {
        filter = "Service.Meta.zone == b"
      }
    }
    failover = {
      "*" = {
        datacenters = "local-dc"
      }
    }
